// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQygL7r7a-LK469oe8jkTp4bOcgFm_Xs4',
    appId: '1:5752589713:web:709e3ef9665df55962de30',
    messagingSenderId: '5752589713',
    projectId: 'chatter-8f557',
    authDomain: 'chatter-8f557.firebaseapp.com',
    storageBucket: 'chatter-8f557.firebasestorage.app',
    measurementId: 'G-1XDEGRJ4TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBJ6OwIZByUIrtmMNR0rYW7Crwjw7H4xw',
    appId: '1:5752589713:android:0f2286a91eb6166d62de30',
    messagingSenderId: '5752589713',
    projectId: 'chatter-8f557',
    storageBucket: 'chatter-8f557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpy7OeRNg2HPoATM0KdMJs7o5jhbZeC8',
    appId: '1:5752589713:ios:9d51c19c5d7aad1862de30',
    messagingSenderId: '5752589713',
    projectId: 'chatter-8f557',
    storageBucket: 'chatter-8f557.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQpy7OeRNg2HPoATM0KdMJs7o5jhbZeC8',
    appId: '1:5752589713:ios:9d51c19c5d7aad1862de30',
    messagingSenderId: '5752589713',
    projectId: 'chatter-8f557',
    storageBucket: 'chatter-8f557.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQygL7r7a-LK469oe8jkTp4bOcgFm_Xs4',
    appId: '1:5752589713:web:f7832b9338ca6c0062de30',
    messagingSenderId: '5752589713',
    projectId: 'chatter-8f557',
    authDomain: 'chatter-8f557.firebaseapp.com',
    storageBucket: 'chatter-8f557.firebasestorage.app',
    measurementId: 'G-1K4MMRNKVZ',
  );
}
